# Generated by Django 6.1 on 2026-08-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='стоимость')),
                ('category', models.CharField(choices=[('docs', 'Документы, визы и гарантии'), ('logistics', 'Международная логистика'), ('adaptation', 'Сопровождение и адаптация в РФ')], max_length=32, verbose_name='категория')),
                ('short_label', models.CharField(blank=True, max_length=80, verbose_name='краткий ярлык')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='стоимость')),
                ('payment_terms', models.TextField(verbose_name='условия оплаты')),
                ('payment_badges', models.JSONField(blank=True, default=list, verbose_name='ярлыки оплаты')),
                ('is_featured', models.BooleanField(default=False, verbose_name='акцентный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('services', models.ManyToManyField(related_name='packages', to='catalog.service', verbose_name='услуги')),
            ],
            options={
                'verbose_name': 'пакет',
                'verbose_name_plural': 'пакеты',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
