# Generated by Django 6.1 on 2026-08-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('citizenship', models.CharField(max_length=120, verbose_name='гражданство')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('payment_method', models.CharField(default='card', max_length=16, verbose_name='способ оплаты')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='последние 4 цифры карты')),
                ('card_brand', models.CharField(blank=True, max_length=32, verbose_name='платёжная система')),
                ('status', models.CharField(choices=[('paid', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='paid', max_length=16, verbose_name='статус')),
                ('offer_accepted', models.BooleanField(default=False, verbose_name='оферта принята')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.service')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='ключ сессии')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.service', verbose_name='услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'позиция корзины',
                'verbose_name_plural': 'корзина',
                'constraints': [models.UniqueConstraint(fields=('session_key', 'service'), name='uniq_cart_session_service')],
            },
        ),
    ]
