# Generated by Django 6.1 on 2026-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='chat id')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='имя')),
                ('authorized_at', models.DateTimeField(auto_now_add=True, verbose_name='авторизован')),
            ],
            options={
                'verbose_name': 'админ Telegram',
                'verbose_name_plural': 'админы Telegram',
            },
        ),
    ]
